#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests-unixsocket
Version  : 0.3.0
Release  : 11
URL      : https://files.pythonhosted.org/packages/c3/ea/0fb87f844d8a35ff0dcc8b941e1a9ffc9eb46588ac9e4267b9d9804354eb/requests-unixsocket-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c3/ea/0fb87f844d8a35ff0dcc8b941e1a9ffc9eb46588ac9e4267b9d9804354eb/requests-unixsocket-0.3.0.tar.gz
Summary  : Use requests to talk HTTP via a UNIX domain socket
Group    : Development/Tools
License  : Apache-2.0
Requires: requests-unixsocket-license = %{version}-%{release}
Requires: requests-unixsocket-python = %{version}-%{release}
Requires: requests-unixsocket-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pbr)
BuildRequires : pypi(requests)

%description
requests-unixsocket
===================
.. image:: https://badge.fury.io/py/requests-unixsocket.svg
:target: https://badge.fury.io/py/requests-unixsocket
:alt: Latest Version on PyPI

.. image:: https://github.com/msabramo/requests-unixsocket/actions/workflows/tests.yml/badge.svg
:target: https://github.com/msabramo/requests-unixsocket/actions/workflows/tests.yml

%package license
Summary: license components for the requests-unixsocket package.
Group: Default

%description license
license components for the requests-unixsocket package.


%package python
Summary: python components for the requests-unixsocket package.
Group: Default
Requires: requests-unixsocket-python3 = %{version}-%{release}

%description python
python components for the requests-unixsocket package.


%package python3
Summary: python3 components for the requests-unixsocket package.
Group: Default
Requires: python3-core
Provides: pypi(requests_unixsocket)
Requires: pypi(requests)

%description python3
python3 components for the requests-unixsocket package.


%prep
%setup -q -n requests-unixsocket-0.3.0
cd %{_builddir}/requests-unixsocket-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640623329
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/requests-unixsocket
cp %{_builddir}/requests-unixsocket-0.3.0/LICENSE %{buildroot}/usr/share/package-licenses/requests-unixsocket/c700a8b9312d24bdc57570f7d6a131cf63d89016
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/requests-unixsocket/c700a8b9312d24bdc57570f7d6a131cf63d89016

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
